#! /bin/bash

FULLSPI=../../Workspace/Prox-AllHARPS.spi

Btchewcalc --interp --divspec 48 8 11 49 51 --out fullresid.ew $FULLSPI

Ewcompar --median --prec 3 --sepd 300 --nopr --latex fullresid.ew

exit 0
prow()
{
	typ="$1"
	descr1="$2"
	descr2="$3"
	descr3="$4"
	echo "$descr1 & \\scipy & `Printpgram --prec 1 --maxn 5 --latex --noendl $typ.ls` \\\\"
	echo "$descr2 & \\astroml & `Printpgram --prec 1 --maxn 5 --latex --noendl $typ.als` \\\\"
	echo "$descr3 & \\gatspy & `Printpgram --prec 1 --maxn 5 --latex --noendl $typ.gls` \\\\\\hline"
}

echo '\begin{tabular}{|l|l|r|r|r|r|r|}'
echo '\hline'
echo '\textbf{Treatment}&\textbf{Routine}&\textbf{Peak 1}&\textbf{Peak 2}&\textbf{Peak 3}&\textbf{Peak 4}&\textbf{Peak 5}\\\hline'
prow Orig "None" "" ""
prow Pruneorig "Clipped" "" ""
prow Bucketorig "Binned" "" ""
prow PBorig "Clipped" "binned" ""
prow origresid "Residuals" "" ""
echo '\end{tabular}'
echo
echo
echo '\begin{tabular}{|l|l|r|r|r|r|r|}'
echo '\hline'
echo '\textbf{Treatment}&\textbf{Routine}&\textbf{Peak 1}&\textbf{Peak 2}&\textbf{Peak 3}&\textbf{Peak 4}&\textbf{Peak 5}\\\hline'
prow Full "None" "" ""
prow Prunefull "Clipped" "" ""
prow Bucketfull "Binned" "" ""
prow PBfull "Clipped" "binned" ""
prow fullresid "Residuals" "" ""
echo '\end{tabular}'

rm -f *.ew *.ls *.als *.gls


