#! /bin/bash

PERIODS=40d:.01d:130d
export PERIODS

ORIGSPI=../../Workspace/Prox-HARPS.spi
FULLSPI=../../Workspace/Prox-AllHARPS.spi

Btchewcalc --interp --out Orig.ew $ORIGSPI
Btchewcalc --interp --out Full.ew $FULLSPI

Btchewcalc --interp --divspec 48 8 11 49 51 --out origresid.ew $ORIGSPI
Btchewcalc --interp --divspec 48 8 11 49 51 --out fullresid.ew $FULLSPI

Pruneew --upper 1 --lower 400 --median Orig.ew Pruneorig.ew
Pruneew --upper 1 --lower 400 --median Full.ew Prunefull.ew

Bucketew --sepdays 1 --lonely 300 Orig.ew Bucketorig.ew
Bucketew --sepdays 1 --lonely 300 Full.ew Bucketfull.ew

Bucketew --sepdays 1 --lonely 300 Pruneorig.ew PBorig.ew
Bucketew --sepdays 1 --lonely 300 Prunefull.ew PBfull.ew

for typ in Orig Pruneorig Bucketorig PBorig origresid Full Prunefull Bucketfull PBfull fullresid
do
	lsconv --type pr --out $typ.ls $typ.ew &
	Alsconv --type pr --out $typ.als $typ.ew &
	Glsconv --type pr --out $typ.gls $typ.ew &
done
wait

prow()
{
	typ="$1"
	descr1="$2"
	descr2="$3"
	descr3="$4"
	echo "$descr1 & \\scipy & `Printpgram --prec 1 --maxn 5 --latex --noendl $typ.ls` \\\\"
	echo "$descr2 & \\astroml & `Printpgram --prec 1 --maxn 5 --latex --noendl $typ.als` \\\\"
	echo "$descr3 & \\gatspy & `Printpgram --prec 1 --maxn 5 --latex --noendl $typ.gls` \\\\\\hline"
}

echo '\begin{tabular}{|l|l|r|r|r|r|r|}'
echo '\hline'
echo '\textbf{Treatment}&\textbf{Routine}&\textbf{Peak 1}&\textbf{Peak 2}&\textbf{Peak 3}&\textbf{Peak 4}&\textbf{Peak 5}\\\hline'
prow Orig "None" "" ""
prow Pruneorig "Clipped" "" ""
prow Bucketorig "Binned" "" ""
prow PBorig "Clipped" "binned" ""
prow origresid "Residuals" "" ""
echo '\end{tabular}'
echo
echo
echo '\begin{tabular}{|l|l|r|r|r|r|r|}'
echo '\hline'
echo '\textbf{Treatment}&\textbf{Routine}&\textbf{Peak 1}&\textbf{Peak 2}&\textbf{Peak 3}&\textbf{Peak 4}&\textbf{Peak 5}\\\hline'
prow Full "None" "" ""
prow Prunefull "Clipped" "" ""
prow Bucketfull "Binned" "" ""
prow PBfull "Clipped" "binned" ""
prow fullresid "Residuals" "" ""
echo '\end{tabular}'

rm -f *.ew *.ls *.als *.gls


