#! /bin/bash

PERIODS=40d:.01d:130d
export PERIODS

ORIGSPI=../../Workspace/Prox-HARPS.spi
FULLSPI=../../Workspace/Prox-AllHARPS.spi

Btchewcalc --interp --out Orig.ew $ORIGSPI
Btchewcalc --interp --out Full.ew $FULLSPI

Kurtcalc --out Orig_ks.ew $ORIGSPI
Kurtcalc --out Full_ks.ew $FULLSPI

Mergeew Orig.ew:1 Orig_ks.ew:1 Orig.ew:3 Orig_skew.ew
Mergeew Full.ew:1 Full_ks.ew:1 Full.ew:3 Full_skew.ew
Mergeew Orig.ew:1 Orig_ks.ew:2 Orig.ew:3 Orig_kurt.ew
Mergeew Full.ew:1 Full_ks.ew:2 Full.ew:3 Full_kurt.ew

Btchewcalc --interp --divspec 48 8 11 49 51 --out origresid.ew $ORIGSPI
Btchewcalc --interp --divspec 48 8 11 49 51 --out fullresid.ew $FULLSPI

Kurtcalc --divspec 48 8 11 49 51 --out orig_resid_ks.ew $ORIGSPI
Kurtcalc --divspec 48 8 11 49 51 --out full_resid_ks.ew $FULLSPI

Mergeew origresid.ew:1 orig_resid_ks.ew:1 origresid.ew:3 orig_resid_skew.ew
Mergeew fullresid.ew:1 full_resid_ks.ew:1 fullresid.ew:3 full_resid_skew.ew
Mergeew origresid.ew:1 orig_resid_ks.ew:2 origresid.ew:3 orig_resid_kurt.ew
Mergeew fullresid.ew:1 full_resid_ks.ew:2 fullresid.ew:3 full_resid_kurt.ew

Pruneew --upper 1 --lower 400 --median Orig_skew.ew Pruneorigskew.ew
Pruneew --upper 1 --lower 400 --median Full_skew.ew Prunefullskew.ew
Pruneew --upper 3.8 --lower 0 --byval Full_skew.ew Prune3p8fullskew.ew
Pruneew --upper 1 --lower 400 --median Orig_kurt.ew Pruneorigkurt.ew
Pruneew --upper 1 --lower 400 --median Full_kurt.ew Prunefullkurt.ew
Pruneew --upper 3.8 --lower 0 --byval Full_kurt.ew Prune3p8fullkurt.ew

Bucketew --sepdays 1 --lonely 300 Orig_skew.ew Bucketorigskew.ew
Bucketew --sepdays 1 --lonely 300 Full_skew.ew Bucketfullskew.ew
Bucketew --sepdays 1 --lonely 300 Orig_kurt.ew Bucketorigkurt.ew
Bucketew --sepdays 1 --lonely 300 Full_kurt.ew Bucketfullkurt.ew
Bucketew --sepdays .5 --lonely 300 Orig_skew.ew Bucketp5origskew.ew
Bucketew --sepdays .5 --lonely 300 Full_skew.ew Bucketp5fullskew.ew
Bucketew --sepdays .5 --lonely 300 Orig_kurt.ew Bucketp5origkurt.ew
Bucketew --sepdays .5 --lonely 300 Full_kurt.ew Bucketp5fullkurt.ew

Bucketew --sepdays 1 --lonely 300 Pruneorigskew.ew PBorigskew.ew
Bucketew --sepdays 1 --lonely 300 Prunefullskew.ew PBfullskew.ew
Bucketew --sepdays 1 --lonely 300 Prune3p8fullskew.ew P3p8Bfullskew.ew
Bucketew --sepdays 1 --lonely 300 Pruneorigkurt.ew PBorigkurt.ew
Bucketew --sepdays 1 --lonely 300 Prunefullkurt.ew PBfullkurt.ew
Bucketew --sepdays 1 --lonely 300 Prune3p8fullkurt.ew P3p8Bfullkurt.ew
Bucketew --sepdays .5 --lonely 300 Pruneorigskew.ew PBp5origskew.ew
Bucketew --sepdays .5 --lonely 300 Prunefullskew.ew PBp5fullskew.ew
Bucketew --sepdays .5 --lonely 300 Prune3p8fullskew.ew P3p8Bp5fullskew.ew
Bucketew --sepdays .5 --lonely 300 Pruneorigkurt.ew PBp5origkurt.ew
Bucketew --sepdays .5 --lonely 300 Prunefullkurt.ew PBp5fullkurt.ew
Bucketew --sepdays .5 --lonely 300 Prune3p8fullkurt.ew P3p8Bp5fullkurt.ew

for ks in skew kurt
do
	for typ in Orig_ Pruneorig Bucketorig Bucketp5orig PBorig PBp5orig orig_resid_ Full_ Prunefull Prune3p8full Bucketfull Bucketp5full PBfull P3p8Bfull PBp5full P3p8Bp5full full_resid_
	do
		lsconv --type ps --out $typ$ks.ls $typ$ks.ew &
		Alsconv --type ps --out $typ$ks.als $typ$ks.ew &
		Glsconv --type ps --out $typ$ks.gls $typ$ks.ew &
	done
done
wait

prow()
{
	typ="$1"
	descr1="$2"
	descr2="$3"
	descr3="$4"
	Printpgram --prec 1 --maxn 5 $typ.ls $typ.als $typ.gls
}

(prow Orig_skew "None" "" ""
prow Pruneorigskew 'Clipped 1$\sigma$' "" ""
prow Bucketorigskew "Binned" "1 day" ""
prow Bucketp5origskew "Binned" "0.5 day" ""
prow PBorigskew 'Clipped 1$\sigma$' "binned" "1 day"
prow PBp5origskew 'Clipped 1$\sigma$' "binned" "0,5 day"
prow orig_resid_skew "Residuals" "" "") >SKO.m5

(prow Orig_kurt "None" "" ""
prow Pruneorigkurt 'Clipped 1$\sigma$' "" ""
prow Bucketorigkurt "Binned" "1 day" ""
prow Bucketp5origkurt "Binned" "0.5 day" ""
prow PBorigkurt 'Clipped 1$\sigma$' "binned" "1 day"
prow PBp5origkurt 'Clipped 1$\sigma$' "binned" "0,5 day"
prow orig_resid_kurt "Residuals" "" "") >KTO.m5

(prow Full_skew "None" "" ""
prow Prunefullskew 'Clipped 1$\sigma$' "" ""
prow Prune3p8fullskew "Clipped" "To 3.8 EW" ""
prow Bucketfullskew "Binned" "1 day" ""
prow Bucketp5fullskew "Binned" "0.5 day" ""
prow PBfullskew "Clipped" '1$\sigma$' "binned 1 day"
prow PBp5fullskew 'Clipped' '1$\sigma$' "binned 0.5 day"
prow P3p8Bfullskew "Clipped" "To 3.8 EW" "binned 1 day"
prow P3p8Bp5fullskew "Clipped" "To 3.8 EW" "binned 0.5 day"
prow full_resid_skew "Residuals" "" "" ) >SKF.m5

(prow Full_kurt "None" "" ""
prow Prunefullkurt 'Clipped 1$\sigma$' "" ""
prow Prune3p8fullkurt "Clipped" "To 3.8 EW" ""
prow Bucketfullkurt "Binned" "1 day" ""
prow Bucketp5fullkurt "Binned" "0.5 day" ""
prow PBfullkurt 'Clipped' '1$\sigma$' "binned 1 day"
prow PBp5fullkurt 'Clipped' '1$\sigma$' "binned 0.5 day"
prow P3p8Bfullkurt "Clipped" "To 3.8 EW" "binned 1 day"
prow P3p8Bp5fullkurt "Clipped" "To 3.8 EW" "binned 0.5 day"
prow full_resid_kurt "Residuals" "" "" ) >KTF.m5

rm -f *.ew *.ls *.als *.gls


